name: Ruff

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: "3.14"
      - name: Install dependencies
        # Keep in sync with .pre-comit-config.yaml
        run: python -Im pip install ruff==0.15.16

      - name: Run ruff
        working-directory: ./src
        run: ruff check --output-format=github wagtail_polymath
